services:
  - type: web
    name: wanderlust-app
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGO_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
